#!/bin/bash
# Add "Great Literacy Characters" above the first line
sed -i '1i\Great Literacy Characters' "$1"
# Add "+1" in front of the phone numbers in the file
sed -ri 's/(:\s*)([0-9]{3}-[0-9]{3}-[0-9]{4})/\11+\2/g' "$1"
# Append "Happily ever after. The end" after the last line of the file
sed -i '$a\Happily ever after. The end' "$1"
# Print the updated file
cat "$1"
